on:
  - push
  - pull_request
name: cabal build
jobs:
  runhaskell:
    name: cabal test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.10', '9.12']
        cabal: ['3.12', '3.14', '3.16']

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: haskell-actions/setup@v2.10.3
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build --dependencies-only --project-file ghc${{ matrix.ghc }}.cabal.project all
      - run: cabal build                     --project-file ghc${{ matrix.ghc }}.cabal.project all
      - run: cabal test                      --project-file ghc${{ matrix.ghc }}.cabal.project all
